"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
[](red)\
$os\
[](bg:peach fg:red)\
$hostname\
$username\
[](bg:yellow fg:peach)\
$directory\
[](bg:green fg:yellow)\
$git_branch\
$git_status\
[](fg:green bg:sapphire)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:sapphire bg:lavender)\
$conda\
[ ](fg:lavender)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Windows = " "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[hostname]
ssh_only = true
style = "bg:peach fg:crust"
ssh_symbol = ' '
format = '[$ssh_symbol$hostname ☠︎]($style)'

[username]
show_always = false
style_user = "bg:peach fg:crust"
style_root = "bg:peach fg:crust"
format = '[ $user ]($style)'

[directory]
style = "bg:yellow fg:crust"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:crust bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:crust bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[c]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[golang]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[php]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[kotlin]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[haskell]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version) ](fg:crust bg:sapphire)]($style)'

[python]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:crust bg:sapphire)]($style)'
detect_extensions = []
detect_files = ['.python-version', 'Pipfile', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
detect_folders = ['.venv', 'venv']

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:crust bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:crust bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = true 
time_format = "%R"
style = "bg:lavender"
format = '[[  $time ](fg:crust bg:lavender)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'

[cmd_duration]
show_milliseconds = false
format = " in $duration "
style = "bg:lavender"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

