"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

# Catppuccin-inspired colors using Starship's basic color names for mosh compatibility
format = """
[](red)\
$os\
[](bg:yellow fg:red)\
$hostname\
$username\
[](bg:bright-yellow fg:yellow)\
$directory\
[](bg:green fg:bright-yellow)\
$git_branch\
$git_status\
[](fg:green bg:cyan)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:cyan bg:purple)\
$conda\
[ ](fg:purple)\
$cmd_duration\
$line_break\
$character"""

[os]
disabled = false
style = "bg:red fg:black"

[os.symbols]
Windows = " "
Ubuntu = "Û∞ïà "
SUSE = " "
Raspbian = "Û∞êø "
Mint = "Û∞£≠ "
Macos = "Û∞Äµ "
Manjaro = " "
Linux = "Û∞åΩ "
Gentoo = "Û∞£® "
Fedora = "Û∞£õ "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = "Û∞£á "
Artix = "Û∞£á "
CentOS = " "
Debian = "Û∞£ö "
Redhat = "Û±Ñõ "
RedHatEnterprise = "Û±Ñõ "

[hostname]
ssh_only = true
style = "bg:yellow fg:black"
ssh_symbol = ' '
format = '[$ssh_symbol$hostname ü´Ü]($style)'

[username]
show_always = false
style_user = "bg:yellow fg:black"
style_root = "bg:yellow fg:black"
format = '[ $user ]($style)'

[directory]
style = "bg:bright-yellow fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "‚Ä¶/"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = " "
"Music" = "Û∞ùö "
"Pictures" = " "
"Developer" = "Û∞≤ã "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:black bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:black bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[c]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[rust]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[golang]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[php]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[java]
symbol = " "
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[kotlin]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[haskell]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version) ](fg:black bg:cyan)]($style)'

[python]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:black bg:cyan)]($style)'
detect_extensions = []
detect_files = ['.python-version', 'Pipfile', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini']
detect_folders = ['.venv', 'venv']

[docker_context]
symbol = ""
style = "bg:cyan"
format = '[[ $symbol( $context) ](fg:black bg:cyan)]($style)'

[conda]
symbol = "  "
style = "fg:black bg:cyan"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = true
time_format = "%R"
style = "bg:purple"
format = '[[  $time ](fg:black bg:purple)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[‚ùØ](bold fg:green)'
error_symbol = '[‚ùØ](bold fg:red)'
vimcmd_symbol = '[‚ùÆ](bold fg:green)'
vimcmd_replace_one_symbol = '[‚ùÆ](bold fg:purple)'
vimcmd_replace_symbol = '[‚ùÆ](bold fg:purple)'
vimcmd_visual_symbol = '[‚ùÆ](bold fg:bright-yellow)'

[cmd_duration]
show_milliseconds = false
format = " in $duration "
style = "bg:purple"
disabled = false
show_notifications = true
min_time_to_notify = 45000
